[package]
name = "x509"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x509-parser = { version = "0.14.0"}
ascii_converter = "0.3.0"